name:                forsyde-project
version:             0.1.0.0
github:              "githubuser/forsyde-project"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/forsyde-project#readme>

dependencies:
- base >= 4.7 && < 5
- forsyde-shallow >= 3.5.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  forsyde-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - forsyde-project

executables:
  2B:
    main: 2B.hs
    source-dirs: src
    dependencies:
      - base
      - forsyde-shallow
  2C:
    main: 2C.hs
    source-dirs: src
    dependencies:
      - base
      - forsyde-shallow

  3A:
    main: 3A.hs
    source-dirs: src
    dependencies:
      - base
      - forsyde-shallow
  4A:
    main: 4A.hs
    source-dirs: src
    dependencies:
      - base
      - forsyde-shallow

  5A:
    main: 5A.hs
    source-dirs: src
    dependencies:
      - base
      - forsyde-shallow

  8A:
    main: 8A.hs
    source-dirs: src
    dependencies:
      - base
      - forsyde-shallow

  9A:
    main: 9A.hs
    source-dirs: src
    dependencies:
      - base
      - forsyde-shallow
      
  9B:
    main: 9B.hs
    source-dirs: src
    dependencies:
      - base
      - forsyde-shallow
